name: dev_polymer
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.10.1

dependencies:
    appwrite: ^20.3.2
    archive: ^4.0.7
    cached_network_image: ^3.4.1
    cupertino_icons: ^1.0.8
    equatable: ^2.0.7
    file_picker: ^8.1.6
    flutter:
        sdk: flutter
    google_fonts: ^6.3.2
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    http: ^1.2.0
    image_picker: ^1.2.1
    intl: ^0.20.2
    path_provider: ^2.1.5
    share_plus: ^12.0.1
    shared_preferences: ^2.5.3
    signature: ^5.5.0
    syncfusion_flutter_pdf: ^31.2.15
    syncfusion_flutter_pdfviewer: ^31.2.15
    syncfusion_flutter_xlsio: ^31.2.18
dev_dependencies:
    build_runner: ^2.4.13
    flutter_lints: ^6.0.0
    flutter_test:
        sdk: flutter
    hive_generator: ^2.0.1

flutter:
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package

    fonts:
        - family: HemiHead
          fonts:
              - asset: assets/fonts/Hemi Head Bd It.otf
